[package]
name = "gershgorin-circle-theorem"
version = "0.1.0"
authors = ["Yossi Frenkel"]
description = "An eigenvalue solver for the Gershgorin Circle Theorem."
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
